### ISSUE TITLE
Add Ticks

### ISSUE THREAD

**Issue by Horselord1** [vonpawn/npc-idle-timer-plugin#1]
Could you add an option to count down in ticks on the npc this would just make more sense as it is already updating the seconds every tick and seems pretty choppy right now.

**Comment by vonpawn** [comment]
I have been out of osrs for about a year now and do not have the dev environment for RL setup on my new PC. If you want to create a pull request with the necessary changes I will work on getting it merged and updated. Otherwise, the change is minor enough that I do not see the juice being worth the squeeze for me to add it.

**Comment by lejeffe** [comment]
This has been added
